# fly.toml app configuration file generated for recipe-app-server on 2023-09-07T18:26:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "recipe-app-server"
primary_region = "bos"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
